GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'baseball'@'%' IDENTIFIED BY 'baseball' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'awsadmin'@'%' IDENTIFIED BY 'Netsys123$' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'mysqladmin'@'%' IDENTIFIED BY 'Netsys123$' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'intern2'@'%' IDENTIFIED BY 'Netsys123$' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'labron'@'%' IDENTIFIED BY 'Netsys123$' WITH GRANT OPTION;
flush privileges;
