#!/bin/bash
echo awsadmin:Netsys123$::::/home/awsadmin:/bin/bash | newusers 
echo cloudadmin:Netsys123$::::/home/cloudadmin:/bin/bash | newusers 
echo mysqladmin:Netsys123$::::/home/mysqladmin:/bin/bash | newusers 
echo mgmt:iloveyou::::/home/mgmt:/bin/bash | newusers
echo bspringsteen:rockandroll::::/home/bspringsteen:/bin/bash | newusers
echo rsyncadmin:catdog::::/home/rsyncadmin:/bin/bash | newusers
echo intern:dragon::::/home/intern:/bin/bash | newusers
echo intern2:dragons::::/home/intern2:/bin/bash | newusers
echo jameson:startupfun::::/home/jameson:/bin/bash | newusers
echo labron:lakers::::/home/labron:/bin/bash | newusers
echo jdaniel:jesus::::/home/jdaniel:/bin/bash | newusers
